# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config

# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:    
  build-infrastructure:
    working_directory: ../jenkins-pipeline/infrastructure
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: EKS infrastructure build
          command: |
            terraform init -input=false
            terraform apply -auto-approve -var-file=variables.tfvars
      - persist_to_workspace:
          root: .
          paths:
            - .

  # build:
  #   docker:
  #     - image: cimg/base:current
  #   steps:
  #     - checkout
  #     - run:
  #         name: Build an artifact
  #         command: touch example.txt
  #     - store_artifacts:
  #         path: example.txt
  # deploy:
  #   docker:
  #     - image: cimg/base:current
  #   steps:
  #     - run:
  #         name: deploy
  #         command: "#e.g. ./deploy.sh"

# # Orchestrate jobs using workflows
workflows:
  build-infrastructure:
    jobs:
      - build-infrastructure
      # - build:
      #     requires:
      #       - build infrastructure
      # # - deploy:
      #     requires:
      #       - test