# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config

# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:    
  build-infrastructure:
    working_directory: ./infrastructure
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            cd infrastructure
            terraform init -input=false
            terraform apply --auto-approve
      - persist_to_workspace:
          root: .
          paths: 
            - .
  
  build-deployment:
    working_directory: ./deployment
    docker:
      - image: cimg/aws:2024.03
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            cd deployment
            terraform init -input=false
          #  echo $AWS_ACCESS_KEY_ID
            terraform plan -var "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" -var "AWS_SECRET_KEY=$AWS_SECRET_KEY"
      - persist_to_workspace:
          root: .
          paths: 
            - .
    
# # Orchestrate jobs using workflowss
workflows:
  build-sock-app:
    jobs:
      - build-infrastructure
      - build-deployment:
           requires:
             - build-infrastructure

#       # - deploy:
      # - build:
      #     requires:
      #       - test


# workflows:
#   build-infrastructure: 
#     jobs:
#       - build-infrastructure:
#       - build-deployment:
#           requires:
#             - build-infrastructure  